// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMaSegk6rw7zN14GtcfBOFhvBpU8km-9k',
    appId: '1:997338622372:android:f0edde77cf6adee5a03931',
    messagingSenderId: '997338622372',
    projectId: 'petshower-b634d',
    storageBucket: 'petshower-b634d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNW7b-guoPPEh4ypWQIu4CCHsaYZMQWnM',
    appId: '1:997338622372:ios:b86051cceb1dd849a03931',
    messagingSenderId: '997338622372',
    projectId: 'petshower-b634d',
    storageBucket: 'petshower-b634d.firebasestorage.app',
    iosBundleId: 'com.example.petShowerControl',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNW7b-guoPPEh4ypWQIu4CCHsaYZMQWnM',
    appId: '1:997338622372:ios:b86051cceb1dd849a03931',
    messagingSenderId: '997338622372',
    projectId: 'petshower-b634d',
    storageBucket: 'petshower-b634d.firebasestorage.app',
    iosBundleId: 'com.example.petShowerControl',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBju0ys3WbhyNuZUM9yx-6geoD6-2RYPts',
    appId: '1:997338622372:web:e55863ab9a5decd2a03931',
    messagingSenderId: '997338622372',
    projectId: 'petshower-b634d',
    authDomain: 'petshower-b634d.firebaseapp.com',
    storageBucket: 'petshower-b634d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBju0ys3WbhyNuZUM9yx-6geoD6-2RYPts',
    appId: '1:997338622372:web:e5c7f12149ab2421a03931',
    messagingSenderId: '997338622372',
    projectId: 'petshower-b634d',
    authDomain: 'petshower-b634d.firebaseapp.com',
    storageBucket: 'petshower-b634d.firebasestorage.app',
  );
}
